languageCode = "en-us"
defaultContentLanguageInSubdir = false
DefaultContentLanguage = "en"

baseurl = "https://appradar.com/"
title = "Some theme title"
theme = ["hugo-slouchy", "hugo-slouchy-base"]

disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "taxonomyTerm"]
buildDrafts = false
preserveTaxonomyNames = true

[Languages]
    [Languages.en]
    weight = 1
    languageCode = "en-us"
    title = "ENGLISH Example site multi-language"
    dateFormat = "January 2, 2006"

    [Languages.de]
    weight = 1
    languageCode = "de-de"
    title = "GERMAN Example site multi-language"
    dateFormat = "2 January, 2006"

[Params]
  debug = true


[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
